export const EMAIL_TEXT_CHANGED = 'EMAIL_TEXT_CHANGED';
export const PASSWORD_TEXT_CHANGED = 'PASSWORD_TEXT_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_START = 'LOGIN_USER_START';
